<a href="https://colab.research.google.com/github/JacksianYun/pytorch_tutorial/blob/master/pytorch_%EB%8F%99%EC%9E%91%ED%99%95%EC%9D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

torch.cuda.is_available()

True

In [0]:
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

In [0]:
linear1 = torch.nn.Linear(128, 5, bias = True)
linear2 = torch.nn.Linear(5, 10, bias = True)
relu = torch.nn.ReLU()

weight1 = list(linear1.parameters())
weight2 = list(linear2.parameters())

In [4]:
print('linear1' , linear1)
print('linear2', linear2)
print('relu', relu)



linear1 Linear(in_features=128, out_features=5, bias=True)
linear2 Linear(in_features=5, out_features=10, bias=True)
relu ReLU()


In [5]:
print(len(weight1))
print(weight1[0].size())
print(weight1[1].size())

2
torch.Size([5, 128])
torch.Size([5])


In [6]:
print(weight1[0][0])
print(weight1[1])

tensor([ 0.0530,  0.0001,  0.0582, -0.0692, -0.0715, -0.0631, -0.0516,  0.0353,
         0.0300,  0.0250,  0.0057, -0.0292,  0.0862, -0.0375,  0.0220,  0.0316,
        -0.0780,  0.0298,  0.0691,  0.0103, -0.0123,  0.0666, -0.0745, -0.0459,
         0.0171,  0.0839, -0.0089,  0.0583,  0.0039, -0.0378, -0.0500, -0.0073,
         0.0668,  0.0541, -0.0197,  0.0640,  0.0468,  0.0689,  0.0109,  0.0477,
        -0.0755,  0.0792, -0.0160, -0.0146,  0.0393,  0.0057, -0.0791, -0.0882,
         0.0516, -0.0376, -0.0047,  0.0721, -0.0856, -0.0046, -0.0466,  0.0766,
        -0.0668,  0.0043, -0.0045,  0.0573,  0.0167, -0.0039, -0.0282,  0.0386,
         0.0882,  0.0780, -0.0677,  0.0512, -0.0415,  0.0200, -0.0172,  0.0193,
         0.0201, -0.0441,  0.0025, -0.0633, -0.0300, -0.0459,  0.0441, -0.0299,
         0.0464,  0.0791, -0.0278,  0.0100, -0.0853,  0.0400, -0.0385, -0.0778,
         0.0340,  0.0829,  0.0102,  0.0479, -0.0764,  0.0756,  0.0774,  0.0261,
        -0.0685, -0.0845,  0.0405, -0.04

In [7]:
input = torch.zeros(1,128)
input[0][0] = 1.
print(input)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])


In [8]:
x1 = linear1(input)
print(x1)

tensor([[ 0.1387, -0.0173, -0.0937, -0.0753,  0.0031]], grad_fn=<ThAddmmBackward>)


In [9]:
print(relu(x1)) 
print(nn.Sigmoid()(x1))
print(nn.LeakyReLU()(x1))


tensor([[0.1387, 0.0000, 0.0000, 0.0000, 0.0031]], grad_fn=<ThresholdBackward0>)
tensor([[0.5346, 0.4957, 0.4766, 0.4812, 0.5008]], grad_fn=<SigmoidBackward>)
tensor([[ 0.1387, -0.0002, -0.0009, -0.0008,  0.0031]], grad_fn=<LeakyReluBackward0>)


In [10]:
x2 = relu(x1)

print(x2)

tensor([[0.1387, 0.0000, 0.0000, 0.0000, 0.0031]], grad_fn=<ThresholdBackward0>)


In [11]:
print(len(weight2))
print(weight2[0].size())
print(weight2[1].size())

2
torch.Size([10, 5])
torch.Size([10])


In [12]:
print(weight2[0][0])
print(weight2[1])

tensor([-0.1238, -0.4442, -0.2129, -0.4220, -0.0520], grad_fn=<SelectBackward>)
Parameter containing:
tensor([-0.0810,  0.4115, -0.0328, -0.2929, -0.0731,  0.3385,  0.2220, -0.2008,
        -0.3089,  0.0350], requires_grad=True)


In [13]:
x3 = linear2(x2) 
print(x3)

tensor([[-0.0984,  0.4262,  0.0035, -0.3297, -0.0368,  0.3191,  0.2838, -0.1502,
         -0.3187,  0.0105]], grad_fn=<ThAddmmBackward>)


In [20]:
print(0.1387* -0.1238 + 0.0031 *  -0.0520 +-0.0810)

-0.09833226


In [15]:
0.4209 - 0.00297402

0.41792598

In [16]:
print(x3.size())

torch.Size([1, 10])


In [21]:

temp_target = torch.tensor([9],dtype=torch.long) 
print(temp_target)


x4 = torch.nn.CrossEntropyLoss()(x3,temp_target)

print(x4)

tensor([9])
tensor(2.3339, grad_fn=<NllLossBackward>)


In [22]:
print(x3)
list_x3 = x3.detach().numpy()
list_exp = np.exp(list_x3[0])
sum_list = np.sum(list_exp)
log_list = np.log(sum_list)

tensor([[-0.0984,  0.4262,  0.0035, -0.3297, -0.0368,  0.3191,  0.2838, -0.1502,
         -0.3187,  0.0105]], grad_fn=<ThAddmmBackward>)


In [23]:
print(x3)
print(list_x3)
print(list_exp)
print(sum_list)
print(log_list)
print(log_list - list_x3[0][9])

tensor([[-0.0984,  0.4262,  0.0035, -0.3297, -0.0368,  0.3191,  0.2838, -0.1502,
         -0.3187,  0.0105]], grad_fn=<ThAddmmBackward>)
[[-0.09836547  0.42618725  0.00346776 -0.3297007  -0.03677908  0.31911832
   0.28382146 -0.15024126 -0.31873325  0.01045728]]
[0.9063176  1.5314075  1.0034738  0.7191389  0.96388906 1.3759141
 1.3281958  0.86050034 0.7270695  1.0105121 ]
10.426419
2.344343
2.3338857
