<a href="https://colab.research.google.com/github/JacksianYun/pytorch_tutorial/blob/master/pytorch_%EB%8F%99%EC%9E%91%ED%99%95%EC%9D%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

torch.cuda.is_available()

True

In [0]:
linear1 = torch.nn.Linear(128, 5, bias = True)
linear2 = torch.nn.Linear(5, 10, bias = True)
relu = torch.nn.ReLU()

weight1 = list(linear1.parameters())
weight2 = list(linear2.parameters())

In [23]:
print('linear1' , linear1)
print('linear2', linear2)
print('relu', relu)



linear1 Linear(in_features=128, out_features=5, bias=True)
linear2 Linear(in_features=5, out_features=10, bias=True)
relu ReLU()


In [24]:
print(len(weight1))
print(weight1[0].size())
print(weight1[1].size())

2
torch.Size([5, 128])
torch.Size([5])


In [29]:
print(weight1[0][0])
print(weight1[1])

tensor([-0.0208, -0.0695, -0.0562, -0.0063, -0.0436,  0.0825,  0.0867, -0.0107,
        -0.0165,  0.0268,  0.0271, -0.0103,  0.0859, -0.0708, -0.0434, -0.0597,
         0.0740, -0.0355, -0.0048, -0.0268, -0.0690, -0.0702, -0.0669,  0.0023,
         0.0272, -0.0311,  0.0365, -0.0808, -0.0409, -0.0384,  0.0658, -0.0427,
        -0.0182, -0.0411,  0.0467,  0.0589, -0.0335, -0.0291, -0.0340,  0.0732,
         0.0346, -0.0470,  0.0858,  0.0315, -0.0121, -0.0651,  0.0301,  0.0567,
        -0.0298,  0.0349,  0.0071,  0.0625,  0.0609, -0.0284, -0.0005, -0.0006,
        -0.0172,  0.0746,  0.0867, -0.0535, -0.0650, -0.0349,  0.0877, -0.0451,
        -0.0649,  0.0500,  0.0267, -0.0134, -0.0878,  0.0543, -0.0299,  0.0178,
        -0.0492,  0.0546, -0.0605,  0.0216, -0.0183,  0.0786,  0.0081, -0.0457,
        -0.0100,  0.0209, -0.0500,  0.0170,  0.0065, -0.0145, -0.0157, -0.0594,
        -0.0773, -0.0451,  0.0703,  0.0389,  0.0569,  0.0212,  0.0507,  0.0091,
         0.0131,  0.0301,  0.0475, -0.01

In [37]:
input = torch.zeros(1,128)
input[0][0] = 1.
print(input)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])


In [38]:
x1 = linear1(input)
print(x1)

tensor([[ 0.0102, -0.0364, -0.0001,  0.0562, -0.0158]], grad_fn=<ThAddmmBackward>)


In [25]:
print(len(weight2))
print(weight2[0].size())
print(weight2[1].size())

2
torch.Size([10, 5])
torch.Size([10])


In [0]:
input = torch.randn(16,8)

In [0]:
result1 = linear1(input.view(-1,16*8))

In [6]:
print(result1)

tensor([[-0.4060,  0.3100,  0.8881, -1.5432,  1.3408]], grad_fn=<ThAddmmBackward>)
